#!/usr/bin/env bash
set -euo pipefail

# Bring up a local Gitea instance via docker-compose, bootstrap an admin user,
# mint an API token, and write a gtx config profile that the rest of the project
# can use for smoke testing.
#
# After this runs successfully:
#   - http://localhost:3333 is the Gitea web UI
#   - The local admin login is "gtx-admin" / "gtx-admin-pw"
#   - scripts/local-gitea/gtx-config.toml has [default] pointing at it
#   - Use it from gtx with:  GTX_CONFIG=scripts/local-gitea/gtx-config.toml gtx ...
#                       or: GITEA_URL=http://localhost:3333 GITEA_TOKEN=... gtx ...
#
# Idempotent: re-running while the container is up reuses the existing token.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ADMIN_USER="gtx-admin"
ADMIN_PW="gtx-admin-pw"
ADMIN_EMAIL="gtx-admin@local.invalid"
TOKEN_NAME="gtx-smoke"
URL="http://localhost:3333"
CONFIG_OUT="$SCRIPT_DIR/gtx-config.toml"

cd "$SCRIPT_DIR"

echo "Starting Gitea container..."
docker compose up -d

echo -n "Waiting for Gitea to be healthy"
for i in $(seq 1 60); do
    if curl -fsS "$URL/api/v1/version" >/dev/null 2>&1; then
        echo " ready!"
        break
    fi
    echo -n "."
    sleep 1
done

if ! curl -fsS "$URL/api/v1/version" >/dev/null 2>&1; then
    echo
    echo "Gitea failed to start. Logs:"
    docker compose logs --tail 40 gitea
    exit 1
fi

# Create the admin user if missing. `gitea admin user create` exits 1 if
# the user exists; ignore that case.
echo "Ensuring admin user $ADMIN_USER exists..."
if ! docker compose exec -u git gitea gitea admin user list 2>/dev/null | awk 'NR>1 {print $2}' | grep -qx "$ADMIN_USER"; then
    docker compose exec -u git gitea gitea admin user create \
        --username "$ADMIN_USER" \
        --password "$ADMIN_PW" \
        --email "$ADMIN_EMAIL" \
        --admin \
        --must-change-password=false
fi

# Mint or reuse an API token. Gitea forbids re-creating a token by the same
# name, so check first.
echo "Minting API token..."
EXISTING="$(curl -fsS -u "$ADMIN_USER:$ADMIN_PW" "$URL/api/v1/users/$ADMIN_USER/tokens" | python3 -c "
import json, sys
data = json.load(sys.stdin)
for t in data:
    if t.get('name') == '$TOKEN_NAME':
        print(t['id'])
        break
" || true)"

if [[ -n "$EXISTING" ]]; then
    echo "Token '$TOKEN_NAME' already exists (id=$EXISTING). Rotating..."
    curl -fsS -X DELETE -u "$ADMIN_USER:$ADMIN_PW" "$URL/api/v1/users/$ADMIN_USER/tokens/$EXISTING" >/dev/null
fi

TOKEN_RESP="$(curl -fsS -X POST -u "$ADMIN_USER:$ADMIN_PW" \
    -H "Content-Type: application/json" \
    "$URL/api/v1/users/$ADMIN_USER/tokens" \
    -d "{\"name\":\"$TOKEN_NAME\",\"scopes\":[\"all\"]}")"

TOKEN="$(printf '%s' "$TOKEN_RESP" | python3 -c "import json,sys; print(json.load(sys.stdin)['sha1'])")"

if [[ -z "$TOKEN" ]]; then
    echo "Failed to mint token. Response: $TOKEN_RESP"
    exit 1
fi

# Write a gtx config profile. This file is gitignored.
cat > "$CONFIG_OUT" <<EOF
# Generated by scripts/local-gitea/up.sh — do not commit.
# This points gtx at the local docker-compose Gitea instance.

[default]
url = "$URL"
token = "$TOKEN"
EOF

chmod 600 "$CONFIG_OUT"

echo
echo "Gitea ready at $URL"
echo "Admin: $ADMIN_USER / $ADMIN_PW"
echo "gtx config written to: $CONFIG_OUT"
echo
echo "To use with gtx for this shell session:"
echo "  export GITEA_URL=$URL"
echo "  export GITEA_TOKEN=$TOKEN"
echo
echo "Or use the config file:"
echo "  cargo run -p gtx -- --help    # if you've copied gtx-config.toml to ~/Library/Application\\ Support/gtx/"
