//! Rust interface to Gitea's Web API, generated by progenitor.
//!
//! # Usage
//!
//! ```no_run
//! use gitea_api::{Auth, Gitea};
//! use url::Url;
//!
//! # async fn example() -> Result<(), Box<dyn std::error::Error>> {
//! let api = Gitea::new(
//!     Auth::Token("your-api-token"),
//!     Url::parse("https://gitea.example.com")?,
//! )?;
//! let version = api.get_version().send().await?.into_inner();
//! println!("Gitea version: {}", version.version.unwrap_or_default());
//! # Ok(())
//! # }
//! ```

// Include the progenitor-generated client code.
include!(concat!(env!("OUT_DIR"), "/codegen.rs"));

pub mod verbose;

/// Deserialize a Vec that may be `null` in JSON (some APIs send `null` for empty arrays).
pub fn null_as_default<'de, D, T>(deserializer: D) -> Result<Vec<T>, D::Error>
where
    D: serde::Deserializer<'de>,
    T: serde::Deserialize<'de>,
{
    use serde::Deserialize;
    let opt: Option<Vec<T>> = Option::deserialize(deserializer)?;
    Ok(opt.unwrap_or_default())
}

/// Errors from the Gitea API client.
#[derive(Debug)]
pub enum GiteaError {
    /// The server answered with a non-success status. `message` is the
    /// server's own reason when the body carried one (Gitea's JSON
    /// `message`, else the body text), falling back to the status's
    /// canonical reason; `url` is the request URL, when known.
    Api {
        status: u16,
        message: String,
        url: Option<String>,
    },
    /// HTTP/reqwest error.
    Http(reqwest::Error),
    /// URL must use http or https scheme.
    HttpRequired,
    /// Authentication key contains non-ASCII characters.
    KeyNotAscii,
}

impl std::fmt::Display for GiteaError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            // Same shape as `gh`: `HTTP 422: <message> (<request url>)`.
            GiteaError::Api {
                status,
                message,
                url,
            } => {
                write!(f, "HTTP {status}: {message}")?;
                if let Some(url) = url {
                    write!(f, " ({url})")?;
                }
                Ok(())
            }
            GiteaError::Http(e) => write!(f, "{e}"),
            GiteaError::HttpRequired => {
                write!(f, "URL must use http:// or https:// scheme")
            }
            GiteaError::KeyNotAscii => {
                write!(f, "authentication key contains non-ASCII characters")
            }
        }
    }
}

impl std::error::Error for GiteaError {}

/// Longest body excerpt shown when an error body isn't Gitea's JSON.
const MAX_RAW_ERROR_CHARS: usize = 200;

/// The server's reason for a failed request: the JSON `message` (plus any
/// `errors` detail), else the body's first line (truncated), else the
/// status's canonical reason.
fn error_message(status: reqwest::StatusCode, body: &str) -> String {
    let reason = || status.canonical_reason().unwrap_or("Error").to_string();
    if let Ok(json) = serde_json::from_str::<serde_json::Value>(body) {
        let message = json["message"].as_str().unwrap_or_default().trim();
        let errors: Vec<&str> = json["errors"]
            .as_array()
            .into_iter()
            .flatten()
            .filter_map(serde_json::Value::as_str)
            .filter(|e| !e.is_empty())
            .collect();
        let message = if message.is_empty() {
            reason()
        } else {
            message.to_string()
        };
        return if errors.is_empty() {
            message
        } else {
            format!("{message}: {}", errors.join("; "))
        };
    }
    let line = body.trim().lines().next().unwrap_or_default().trim();
    // An HTML page (proxy error, login redirect) says nothing useful inline.
    if line.is_empty() || line.starts_with('<') {
        return reason();
    }
    match line.char_indices().nth(MAX_RAW_ERROR_CHARS) {
        Some((cut, _)) => format!("{}…", &line[..cut]),
        None => line.to_string(),
    }
}

impl GiteaError {
    /// Build the error for a failed response from its parts.
    pub fn from_body(status: reqwest::StatusCode, url: Option<&str>, body: &str) -> Self {
        GiteaError::Api {
            status: status.as_u16(),
            message: error_message(status, body),
            url: url.map(str::to_string),
        }
    }

    /// Consume a failed response, reading its body for the server's reason.
    pub async fn from_response(resp: reqwest::Response) -> Self {
        let status = resp.status();
        if let Some(captured) = resp.extensions().get::<verbose::ErrorBody>() {
            return Self::from_body(status, Some(&captured.url), &captured.body);
        }
        let url = resp.url().to_string();
        let body = resp.text().await.unwrap_or_default();
        Self::from_body(status, Some(&url), &body)
    }
}

/// Pass a successful response through; turn a failed one into
/// [`GiteaError::Api`] carrying the server's reason.
pub async fn error_for_status(resp: reqwest::Response) -> Result<reqwest::Response, GiteaError> {
    if resp.status().is_success() {
        Ok(resp)
    } else {
        Err(GiteaError::from_response(resp).await)
    }
}

impl<E: std::fmt::Debug> From<progenitor_client::Error<E>> for GiteaError {
    fn from(e: progenitor_client::Error<E>) -> Self {
        // The client's `exec` hook buffers every failed response's body into
        // an `ErrorBody` extension (see `verbose.rs`), so it can be read
        // here without awaiting.
        if let progenitor_client::Error::UnexpectedResponse(resp) = &e
            && let Some(captured) = resp.extensions().get::<verbose::ErrorBody>()
        {
            return Self::from_body(resp.status(), Some(&captured.url), &captured.body);
        }
        match e.status() {
            Some(status) => Self::from_body(status, None, ""),
            None => GiteaError::Api {
                status: 0,
                message: e.to_string(),
                url: None,
            },
        }
    }
}

impl From<reqwest::Error> for GiteaError {
    fn from(e: reqwest::Error) -> Self {
        GiteaError::Http(e)
    }
}

/// Method of authentication.
pub enum Auth<'a> {
    /// API access token.
    Token(&'a str),
    /// No authentication.
    None,
}

impl Auth<'_> {
    fn to_headers(&self) -> Result<reqwest::header::HeaderMap, GiteaError> {
        let mut headers = reqwest::header::HeaderMap::new();
        match self {
            Auth::Token(token) => {
                let mut header: reqwest::header::HeaderValue = format!("token {token}")
                    .try_into()
                    .map_err(|_| GiteaError::KeyNotAscii)?;
                header.set_sensitive(true);
                headers.insert("Authorization", header);
            }
            Auth::None => (),
        }
        Ok(headers)
    }
}

/// Wrapper around the progenitor-generated [`Client`] that adds authentication.
pub struct Gitea {
    client: Client,
    reqwest_client: reqwest::Client,
    base_url: String,
}

impl Gitea {
    /// Create a new client connected to the specified Gitea instance.
    pub fn new(auth: Auth, url: url::Url) -> Result<Self, GiteaError> {
        if !matches!(url.scheme(), "http" | "https") {
            return Err(GiteaError::HttpRequired);
        }

        // Auth is injected per-request via the `ClientHooks::pre` hook so
        // verbose transcripts can see the header. (Setting it via
        // `default_headers` works at the wire level, but the Authorization
        // value never lands on the `reqwest::Request` object inspected by
        // hooks.)
        let auth_headers = auth.to_headers()?;
        verbose::set_auth_headers(auth_headers);

        let reqwest_client = reqwest::Client::builder()
            .user_agent("gitea-api-rs")
            .build()
            .expect("failed to build reqwest client");

        // The OAS3 spec declares servers: [{"url": "{base}/api/v1"}],
        // so the base URL for the progenitor client is {instance_url}/api/v1.
        let mut base_url = url.to_string();
        if !base_url.ends_with('/') {
            base_url.push('/');
        }
        base_url.push_str("api/v1");

        let client = Client::new_with_client(&base_url, reqwest_client.clone());
        Ok(Self {
            client,
            reqwest_client,
            base_url,
        })
    }

    /// Make a raw GET request to a Gitea API path (e.g., "repos/owner/repo/projects").
    /// Auth headers are included automatically. Returns error on non-success status.
    pub async fn raw_get(&self, path: &str) -> Result<String, GiteaError> {
        let url = format!("{}/{}", self.base_url, path.trim_start_matches('/'));
        let mut req = self.reqwest_client.get(&url).build()?;
        verbose::apply_auth_headers(&mut req);
        let resp = self.reqwest_client.execute(req).await?;
        Ok(error_for_status(resp).await?.text().await?)
    }

    /// Make a raw request with method, path, and optional JSON body.
    pub async fn raw_request(
        &self,
        method: reqwest::Method,
        path: &str,
        body: Option<&serde_json::Value>,
    ) -> Result<reqwest::Response, GiteaError> {
        let url = format!("{}/{}", self.base_url, path.trim_start_matches('/'));
        let mut req = self.reqwest_client.request(method, &url);
        if let Some(body) = body {
            req = req.header("Content-Type", "application/json").json(body);
        }
        let mut built = req.build()?;
        verbose::apply_auth_headers(&mut built);
        Ok(self.reqwest_client.execute(built).await?)
    }

    /// GET an absolute URL outside the API, such as an attachment's
    /// `browser_download_url` (a web route that redirects to the login page
    /// without credentials). Auth headers are sent only when the URL shares
    /// this instance's origin, so the token never goes to a foreign host.
    pub async fn download(&self, url: &str) -> Result<reqwest::Response, GiteaError> {
        let mut req = self.reqwest_client.get(url).build()?;
        let same_origin =
            url::Url::parse(&self.base_url).is_ok_and(|base| base.origin() == req.url().origin());
        if same_origin {
            verbose::apply_auth_headers(&mut req);
        }
        Ok(self.reqwest_client.execute(req).await?)
    }

    /// Make a fully customizable request. Used by `gtx api` for arbitrary endpoints
    /// with custom headers, methods, and bodies. The body goes out verbatim,
    /// as `Content-Type: application/json` unless `headers` sets one.
    pub async fn request(
        &self,
        method: reqwest::Method,
        url: &str,
        headers: &[(String, String)],
        body: Option<&[u8]>,
    ) -> Result<reqwest::Response, GiteaError> {
        let mut req = self.reqwest_client.request(method, url);
        req = req.header("Accept", "application/json");
        for (key, value) in headers {
            req = req.header(key.as_str(), value.as_str());
        }
        if let Some(body) = body {
            if !headers
                .iter()
                .any(|(key, _)| key.eq_ignore_ascii_case("content-type"))
            {
                req = req.header("Content-Type", "application/json");
            }
            req = req.body(body.to_vec());
        }
        let mut built = req.build()?;
        verbose::apply_auth_headers(&mut built);
        if let Some(cfg) = verbose::config()
            && cfg.is_on()
        {
            verbose::print_request(&built, None, cfg);
        }
        let resp = self.reqwest_client.execute(built).await?;
        if let Some(cfg) = verbose::config()
            && cfg.is_on()
        {
            verbose::print_response_head(&resp, cfg);
        }
        Ok(resp)
    }

    /// Build a full URL from an API path (prepends base_url).
    pub fn url_for(&self, path: &str) -> String {
        format!("{}/{}", self.base_url, path.trim_start_matches('/'))
    }

    /// Get the base URL (e.g., "https://gitea.example.com/api/v1").
    pub fn base_url(&self) -> &str {
        &self.base_url
    }
}

// Re-export reqwest types that callers need
pub use reqwest::Method;
pub use reqwest::Response;

impl std::ops::Deref for Gitea {
    type Target = Client;
    fn deref(&self) -> &Client {
        &self.client
    }
}
